In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import sklearn as sk
from sklearn.neighbors import KNeighborsClassifier

In [3]:
import sys
print(sys.version)
print(sys.path)

3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:29:51) [MSC v.1929 64 bit (AMD64)]
['c:\\Users\\Xsper\\Documents\\GitHub\\ACM-AI', 'c:\\Users\\Xsper\\miniconda3\\envs\\acm-ai\\python310.zip', 'c:\\Users\\Xsper\\miniconda3\\envs\\acm-ai\\DLLs', 'c:\\Users\\Xsper\\miniconda3\\envs\\acm-ai\\lib', 'c:\\Users\\Xsper\\miniconda3\\envs\\acm-ai', '', 'c:\\Users\\Xsper\\miniconda3\\envs\\acm-ai\\lib\\site-packages', 'c:\\Users\\Xsper\\miniconda3\\envs\\acm-ai\\lib\\site-packages\\win32', 'c:\\Users\\Xsper\\miniconda3\\envs\\acm-ai\\lib\\site-packages\\win32\\lib', 'c:\\Users\\Xsper\\miniconda3\\envs\\acm-ai\\lib\\site-packages\\Pythonwin']


In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
print(iris.feature_names)
print(iris.target)
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


## Requirements for working with data in scikit-learn
1. Features and response are separate objects
2. Features and response should be numeric
3. Features and response should be NumPy arrays
4. Features and response should have specific shapes

In [6]:
predictors = iris.data
label = iris.target

In [7]:
knn = KNeighborsClassifier(n_neighbors=1)

In [8]:
knn.fit(predictors, label)

KNeighborsClassifier(n_neighbors=1)

In [9]:
knn.predict([[3, 5, 4, 2]])

array([2])

In [10]:
iris_labels = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(iris_labels)

array([2, 1])

In [11]:
knn2 = KNeighborsClassifier(n_neighbors=5)

In [12]:
knn2.fit(predictors, label)

KNeighborsClassifier()

In [13]:
knn2.predict(iris_labels)

array([1, 1])

## Using a different model in scikit-learn

In [14]:
from sklearn.linear_model import LogisticRegression
logreq = LogisticRegression(solver='lbfgs', max_iter=1000)

In [15]:
logreq.fit(predictors, label)

LogisticRegression(max_iter=1000)

In [16]:
logreq.predict(iris_labels)

array([0, 0])